[package]
name = "rhai-workaround"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
map-macro = "0.2.6"
rhai = { version = "1.15.1", features = ["only_i32"] }
